export const GET_ALL_WORKSHOPS = "GET_ALL_WORKSHOPS";
export const GET_APPROVED_WORKSHOPS = "GET_APPROVED_WORKSHOPS"
export const GET_PENDING_WORKSHOPS = "GET_PENDING_WORKSHOPS"
export const GET_REJECTED_WORKSHOPS = "GET_REJECTED_WORKSHOPS"
export const APPROVED_WORKSHOP = "APPROVED_WORKSHOP"
export const REJECTED_WORKSHOP = "REJECTED_WORKSHOP"
export const GET_DETAIL_WORKSHOP = "GET_DETAIL_WORKSHOP"
