export const SET_CANDIDATE = "SET_CANDIDATE";
export const UPDATE_CANDIDATE = "UPDATE_CANDIDATE";
export const SET_CANDIDATE_DETAILS = "SET_CANDIDATE_DETAILS";
export const SET_CANDIDATE_PAGE = "SET_CANDIDATE_PAGE";