export const SET_CANDIDATE = "SET_CANDIDATE";
export const UPDATE_CANDIDATE = "UPDATE_CANDIDATE";
export const SET_CANDIDATE_DETAILS = "SET_CANDIDATE_DETAILS";
export const SET_CANDIDATE_PAGE = "SET_CANDIDATE_PAGE";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const FOLLOW_CHECK = "FOLLOW_CHECK";
export const FOLLOW_COUNT = "FOLLOW_COUNT";
export const FOLLOW_LIST = "FOLLOW_LIST";