export const SET_COOPERATION = "SET_COOPERATION";
export const SET_COOPERATION_ID = "SET_COOPERATION_ID";
export const APPROVE_COOPERATION = "APPROVE_COOPERATION";
export const REJECT_COOPERATION = "REJECT_COOPERATION";