export const SET_EMPLOYEE = "SET_EMPLOYEE";
export const SET_EMPLOYEE_ID = "SET_EMPLOYEE";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";