export const SET_INDUSTRIES = "SET_INDUSTRIES";
export const SET_INDUSTRY_OPTIONS = "SET_INDUSTRY_OPTIONS";
export const CREATE_INDUSTRIES = "CREATE_INDUSTRIES";
export const GET_INDUSTRIES_DETAIL = "GET_INDUSTRIES_DETAIL";