export const SET_INSTRUCTIONAL = 'SET_INSTRUCTIONAL'
export const SET_SELECTED_ID ='SET_SELECTED_IDS'
export const UPDATE_INSTRUCTIONAL ='UPDATE_INSTRUCTIONAL'
export const TOTAL_INSTRUCTIONAL ='TOTAL_INSTRUCTIONAL'