export const SET_SECTIONS = "SET_SECTIONS";
export const CREATE_SECTION = "CREATE_SECTION";
export const DELETE_SECTION = "DELETE_SECTION";
export const UPDATE_SECTION_ID = "UPDATE_SECTION_ID"
export const TOTAL_SECTION ='TOTAL_SECTION'
export const COUNT_SECTION_MAJOR ='COUNT_SECTION_MAJOR'