export const SET_UNIVERSITY = "SET_UNIVERSITY";
export const UPDATE_UNIVERSITY = "UPDATE_UNIVERSITY";
export const SET_UNIVERSITY_DETAILS = "SET_UNIVERSITY_DETAILS";
export const SET_UNIVERSITY_PAGE = "SET_UNIVERSITY_PAGE";